### ISSUE TITLE
frontend ==> CHAT the user right panel is not well displayed when resizing

### ISSUE THREAD

**Issue by vbachele** [vbachele/ft_transcendence_42#188]
![Image](https://user-images.githubusercontent.com/62295364/228201100-06490cfd-8b34-4304-8f49-4f7a1c061923.png)

**Comment by antoroll** [comment]
done

**Comment by vbachele** [comment]
je rouvre le ticket le bug est toujours present apres le merge et quand tu resizes ca refonctionne mais le message a disparu
