### ISSUE TITLE
Main not compiling AGAIN

### ISSUE THREAD

**Issue by louisnfr** [vbachele/ft_transcendence_42#69]
je dois supp tous les `as { id: string }` dans `backend.ts` sinon ca compile pas
![image](https://user-images.githubusercontent.com/57815912/219518593-43910250-f713-4197-94d0-1858bcdcbca0.png)

**Comment by louisnfr** [comment]
quand j'essaie de migrate la db
![image](https://user-images.githubusercontent.com/57815912/219518266-df1173d3-7bef-4301-9150-26f3ef724d41.png)

quand je vais sur la db
![image](https://user-images.githubusercontent.com/57815912/219518373-ea357a81-414a-432f-9cf9-62f7477f4699.png)

quand je vais sur /leaderboard
![image](https://user-images.githubusercontent.com/57815912/219518306-64f9f886-65ef-4d0a-a77b-1c91fd3c1316.png)

**Comment by vbachele** [comment]
On en discute a notre daily alors messire pour me montrer
